
select * from my_table limit 20

--total revenue generated by male vs. female customers
select gender , SUM(purchase_amount) as revenue
from my_table
group by gender 

--discount  but still spent more than the average purchase amount
select customer_id,purchase_amount
from my_table 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from my_table)

--top 5 products whit the highest average review rating 
select item_purchased,ROUND(AVG(review_rating::numeric),2)as "Average Product Rating"
from my_table
group by item_purchased 
order by AVG(review_rating) des